# @package _global_
evolution:
  elite_ratio: 0.1
  rl_injection_interval: 10
  eval_trials: 1
surrogate:
  epsilon: 0.146
  mad_k: 1.513
  beta: 0.434
  omega: 0.700
  k: 2048
  dropout_p: 0.340
  mc_samples: 10
  k_ensembles: 4
rl:
  policy_noise: 0.173
  noise_clip: 0.593
  policy_delay: 1
