# @package _global_
evolution:
  elite_ratio: 0.1
  rl_injection_interval: 10
  eval_trials: 1
surrogate:
  beta: 4.581
  omega: 0.620
  k: 5120
  epsilon: 0.173
  mad_k: 3.316
  dropout_p: 0.331
  mc_samples: 43
  lam: 0.1
  k_ensembles: 8
rl:
  policy_noise: 0.126
  noise_clip: 0.373
  policy_delay: 4