# @package _global_
evolution:
  elite_ratio: 0.2
  rl_injection_interval: 1
  eval_trials: 5
surrogate:
  epsilon: 0.142
  mad_k: 2.483
  beta: 0.432
  omega: 0.549
  k: 1024
  dropout_p: 0.252
  mc_samples: 48
  k_ensembles: 9
rl:
  policy_noise: 0.206
  noise_clip: 0.562
  policy_delay: 1
warmup:
  warmup_steps: 25000