# @package _global_
evolution:
  elite_ratio: 0.2
  rl_injection_interval: 1
  eval_trials: 3
surrogate:
  epsilon: 0.036
  mad_k: 1.188
  beta: 0.208
  omega: 0.366
  k: 6144
  dropout_p: 0.343
  mc_samples: 13
  k_ensembles: 3
rl:
  policy_noise: 0.247
  noise_clip: 0.710
  policy_delay: 1
warmup:
  warmup_steps: 25000