# @package _global_
name: erl
buffer_size: 200000
n_steps: 1000000
batch_size: 256

network:
  actor_hidden_dim: 256
  critic_hidden_dim: 256

rl:
  gamma: 0.99
  tau: 0.005
  actor_lr: 3e-4
  critic_lr: 3e-4
  exploration_noise_std: 0.1
  gradient_steps: 1000

evolution:
  population_size: 10
  mutation_std: 0.1      
  mutation_prob: 0.9    
  elite_ratio: 0.2       
  rl_injection_interval: 1 

evaluation:
  evaluate_episodes: 5
  
warmup:
  warmup_steps: 10000
