# @package _global_
name: erl

population_size: 10
buffer_size: 200_000
n_steps: 1_000_000
batch_size: 256

network:
  hidden_dim: 256

rl:
  gamma: 0.99
  tau: 0.005
  actor_lr: 3e-4
  critic_lr: 3e-4
  exploration_noise_std: 0.1
  gradient_steps: 50

evolution:
  mutation_std: 0.05
  mutation_prob: 0.1
  elite_ratio: 0.2
  rl_injection_interval: 10

evaluation:
  evaluate_episodes: 5

warmup:
  warmup_steps: 10_000
