defaults:
- algorithm: erl
- _self_
seed: 0
device: auto
debug: false
grad_clip_norm: 10.0
env:
  id: Swimmer-v5
eval_env:
  id: Swimmer-v5
wandb:
  enabled: true
  project: ue_evo_rl_2
  entity: evo_rl
  name: null
  tags: []
