defaults:
- algorithm: erl
- _self_
seed: 0
device: auto
debug: false
grad_clip_norm: 1.0
env:
  id: FetchPush-v4
eval_env:
  id: FetchPush-v4
wandb:
  enabled: true
  project: evo_rl
  entity: new_tests
  name: null
  tags: []
