wandb:
  entity: evo_rl
  project: ue_evo_rl_3

algorithms:
  - sc_erl_evidential
  - sc_erl_dropout
  - sc_erl_ensemble
  - sc_erl_random
  - td3
  - erl
  - ppo
  - ddpg
  - sac
  - crossq
  - wimle

environments:
  - HalfCheetah-v5
  - Hopper-v5
  - Walker2d-v5
  - Ant-v5
  - Swimmer-v5
  - dm_control_dog-stand-v0
  - dm_control_dog-walk-v0
  - dm_control_dog-trot-v0
  - dm_control_dog-run-v0
  - dm_control_dog-fetch-v0
