wandb:
  entity: evo_rl
  project: FINAL

algorithms:
  - sc_erl_dropout
  - sc_erl_ensemble
  - sc_erl_random
  - td3
  - erl
  - ppo
  - ddpg

environments:
  - HalfCheetah-v4
  - Hopper-v4
  - Walker2d-v4
  - Ant-v4
  - Swimmer-v4
