import os
import re
from fpdf import FPDF


def translate_header(header):
    """Maps W&B CSV column headers to readable English labels for the PDF report tables."""
    header = header.strip()
    translations = {
        'Algorithm/Method': 'Method / Algorithm',
        'Eval_Reward_Mean': 'Mean Eval Reward',
        'Eval_Reward_Std': 'Std Eval Reward',
        'Best_Pop_Fitness_Mean': 'Mean Best Pop Fitness',
        'Best_Pop_Fitness_Std': 'Std Best Pop Fitness',
        'Pearson Correlation': 'Pearson Correlation',
        'Spearman Correlation': 'Spearman Correlation',
        'Sample Size (N)': 'Sample Size (N)',
        # Legacy Polish keys kept for compatibility with older .tex files
        'Metoda / Algorytm': 'Method / Algorithm',
        'Srednia Nagroda Ew.': 'Mean Eval Reward',
        'Odch. Std Nagrody Ew.': 'Std Eval Reward',
        'Sr. Najlepsza Sprawnosc': 'Mean Best Pop Fitness',
        'Odch. Std Sprawnosci': 'Std Best Pop Fitness',
        'Korelacja Pearsona': 'Pearson Correlation',
        'Korelacja Spearmana': 'Spearman Correlation',
        'Rozmiar Probki (N)': 'Sample Size (N)',
    }
    return translations.get(header, header)


def parse_tex_table_to_data(filepath):
    """
    Parses a LaTeX tabular block generated by Pandas .style.to_latex() into a list of rows.
    Returns None if the file does not exist or the tabular block cannot be found.
    Strips LaTeX control sequences and unescapes common special characters.
    """
    if not os.path.exists(filepath):
        print(f'Warning: {filepath} does not exist.')
        return None

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    tabular_match = re.search(r'\\begin{tabular}{.*?}(.*?)\\end{tabular}', content, re.DOTALL)
    if not tabular_match:
        print(f'Warning: Could not parse tabular block in {filepath}')
        return None

    tabular_content = tabular_match.group(1).strip()
    lines = tabular_content.split('\n')
    rows = []

    for line in lines:
        line = line.strip()
        if not line:
            continue
        # Skip LaTeX horizontal rule commands
        if any(line.startswith(cmd) for cmd in ['\\toprule', '\\midrule', '\\bottomrule', '\\hline']):
            continue

        # Strip trailing row-end markers (e.g. "\\", "\\ [2pt]")
        clean_line = re.sub(r'\\\\(\s*\[.*?\])?', '', line).strip()

        # Unescape common LaTeX special characters
        clean_line = (
            clean_line
            .replace('\\%', '%')
            .replace('\\_', '_')
            .replace('\\&', '&')
            .replace('\\#', '#')
        )

        cols = [c.strip() for c in clean_line.split('&')]
        if len(cols) > 0 and any(cols):
            # First row is always the header — translate column labels to English
            if not rows:
                cols = [translate_header(c) for c in cols]
            rows.append(cols)

    return rows


def sanitize_text(text):
    """
    Encodes text to latin-1 and back, replacing any character outside the
    supported range with '?' to prevent FPDFUnicodeEncodingException.
    Helvetica (core PDF font) only supports latin-1 (ISO 8859-1).
    """
    return text.encode('latin-1', errors='replace').decode('latin-1')

class ERLReportPDF(FPDF):
    """
    Custom FPDF subclass for the SC-ERL experiment report.
    Uses only PDF-core built-in fonts (Helvetica) to ensure full cross-platform
    compatibility on macOS, Linux servers, and HPC clusters without requiring
    external .ttf font files.

    All text strings are in ASCII-safe English to stay within the latin-1
    character range supported by Helvetica core fonts.
    """

    def header(self):
        self.set_y(10)
        # Helvetica is a built-in PDF core font — no .ttf installation required
        self.set_font('Helvetica', 'B', 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, 'EVOLUTIONARY REINFORCEMENT LEARNING - STATISTICAL REPORT', border=0, align='L')
        self.set_x(15)
        self.cell(0, 5, 'EXPERIMENT SUMMARY', border=0, align='R')
        self.ln(5)
        self.set_draw_color(220, 220, 220)
        self.line(15, 16, 195, 16)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', align='C')

    def section_title(self, label):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, label, new_x='LMARGIN', new_y='NEXT')
        self.ln(1)

    def subsection_title(self, label):
        self.set_font('Helvetica', 'B', 10.5)
        self.set_text_color(80, 80, 80)
        self.cell(0, 8, label, new_x='LMARGIN', new_y='NEXT')
        self.ln(1)

    def draw_data_table(self, rows):
        """
        Renders a parsed LaTeX table as a formatted FPDF2 table using the context manager API.
        Automatically handles row wrapping and column alignment via fpdf2's built-in layout engine.
        """
        if not rows:
            return
        self.set_font('Helvetica', size=8)
        self.set_text_color(0, 0, 0)
        with self.table(
            borders_layout='HORIZONTAL_LINES',
            cell_fill_color=(255, 255, 255),
            cell_fill_mode='ROWS',
            line_height=5.5,
        ) as table:
            # Render header row in bold
            header_row = table.row()
            self.set_font('Helvetica', 'B', 8)
            for col in rows[0]:
                header_row.cell(sanitize_text(col))
            # Render data rows in lighter font
            self.set_font('Helvetica', size=7.5)
            self.set_text_color(50, 50, 50)
            for row in rows[1:]:
                data_row = table.row()
                for item in row:
                    data_row.cell(sanitize_text(item))
        self.ln(4)

    def ensure_space_or_break(self, required_h):
        """
        Checks if at least `required_h` mm of vertical space remains before the page break trigger.
        If not enough space is available, forces a new page to prevent content from overflowing
        into the footer area or beyond the printable margin.
        """
        if self.get_y() + required_h > self.page_break_trigger:
            self.add_page()


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    results_dir = os.path.join(project_root, 'results')

    # Load environment list from the download config if available; otherwise scan results dir
    from omegaconf import OmegaConf
    config_path = os.path.join(project_root, 'configs', 'download.yaml')
    if os.path.exists(config_path):
        config = OmegaConf.load(config_path)
        environments = list(config.environments)
    else:
        environments = [
            d for d in os.listdir(results_dir)
            if os.path.isdir(os.path.join(results_dir, d))
        ]

    # Initialize PDF using built-in Helvetica — no external font files required
    pdf = ERLReportPDF(orientation='P', unit='mm', format='A4')
    pdf.set_margins(15, 20, 15)
    pdf.alias_nb_pages()

    for env in environments:
        env_dir = os.path.join(results_dir, env)
        print(f'Processing environment {env}...')

        # -----------------------------------------------------------------------
        # PAGE 1: Summary tables (always created — tables are the primary output)
        # -----------------------------------------------------------------------
        pdf.add_page()
        pdf.section_title(f'Environment: {env}')

        summary_tex = os.path.join(env_dir, f'{env}_summary_table.tex')
        if os.path.exists(summary_tex):
            pdf.subsection_title('Summary Results Table')
            summary_data = parse_tex_table_to_data(summary_tex)
            if summary_data:
                pdf.draw_data_table(summary_data)

        sig_tex = os.path.join(env_dir, f'{env}_significance_table.tex')
        if os.path.exists(sig_tex):
            pdf.subsection_title('Statistical Significance Table')
            sig_data = parse_tex_table_to_data(sig_tex)
            if sig_data:
                pdf.draw_data_table(sig_data)

        corr_tex = os.path.join(env_dir, f'{env}_critic_correlation.tex')
        if os.path.exists(corr_tex):
            pdf.subsection_title('Critic Correlation Analysis')
            corr_data = parse_tex_table_to_data(corr_tex)
            if corr_data:
                pdf.draw_data_table(corr_data)

        # -----------------------------------------------------------------------
        # PAGE 2: Sample efficiency curve (created ONLY if the image file exists)
        # -----------------------------------------------------------------------
        eff_img = os.path.join(env_dir, f'{env}_sample_efficiency.png')
        if os.path.exists(eff_img):
            pdf.add_page()
            pdf.section_title(f'{env} - Results and Analysis Plots')
            pdf.ln(5)
            pdf.subsection_title('1. Sample Efficiency Curve')
            y_before = pdf.get_y()
            pdf.image(eff_img, x=25, y=y_before, w=160, h=95)
            pdf.set_y(y_before + 98)
            pdf.ln(5)

        # -----------------------------------------------------------------------
        # PAGE 3: Surrogate & correlation plots (created ONLY if at least one exists)
        # -----------------------------------------------------------------------
        surr_img = os.path.join(env_dir, f'{env}_surrogate_analysis.png')
        corr_img = os.path.join(env_dir, f'{env}_critic_correlation.png')

        if os.path.exists(surr_img) or os.path.exists(corr_img):
            pdf.add_page()
            pdf.section_title(f'{env} - Surrogate and Correlation Analysis')
            pdf.ln(5)

            if os.path.exists(surr_img):
                # Guard: ensure surrogate plot (60 mm tall) fits before placing it
                pdf.ensure_space_or_break(65)
                pdf.subsection_title('2. Surrogate Uncertainty Analysis')
                y_before = pdf.get_y()
                pdf.image(surr_img, x=25, y=y_before, w=160, h=60)
                pdf.set_y(y_before + 63)
                pdf.ln(5)

            if os.path.exists(corr_img):
                # Guard: ensure correlation plot (55 mm tall) fits before placing it
                pdf.ensure_space_or_break(65)
                pdf.subsection_title('3. Critic Correlation Plot')
                y_before = pdf.get_y()
                pdf.image(corr_img, x=25, y=y_before, w=160, h=55)
                pdf.set_y(y_before + 58)
                pdf.ln(5)

    pdf_output_path = os.path.join(project_root, 'full_report.pdf')
    pdf.output(pdf_output_path)
    print(f'Report generated successfully: {pdf_output_path}')


if __name__ == '__main__':
    main()